language: python

python:
  - "2.7"

addons:
  apt:
    packages:
    - ipython
    - python-numpy
    - python-scipy
    - python-matplotlib
    - python-pandas

install:
  - pip install git+https://github.com/G-Node/python-odml.git
  - pip install --no-dependencies  -r requirements.txt
  - pip install nose nose-cov python-coveralls

# command to run tests
script:
  - nosetests -vv --with-coverage --cover-package=thunderfish
after_success:
  - coveralls
